package com.model.entity;

import lombok.ToString;

import java.io.Serializable;
import java.util.Date;

@ToString
public class JdComputer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_computer.id
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_computer.code
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_computer.money
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_computer.name
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_computer.status
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_computer.creatime
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    private Date creatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_computer.endtime
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_computer.id
     *
     * @return the value of jd_computer.id
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_computer.id
     *
     * @param id the value for jd_computer.id
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_computer.code
     *
     * @return the value of jd_computer.code
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_computer.code
     *
     * @param code the value for jd_computer.code
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_computer.money
     *
     * @return the value of jd_computer.money
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_computer.money
     *
     * @param money the value for jd_computer.money
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_computer.name
     *
     * @return the value of jd_computer.name
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_computer.name
     *
     * @param name the value for jd_computer.name
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_computer.status
     *
     * @return the value of jd_computer.status
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_computer.status
     *
     * @param status the value for jd_computer.status
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_computer.creatime
     *
     * @return the value of jd_computer.creatime
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_computer.creatime
     *
     * @param creatime the value for jd_computer.creatime
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_computer.endtime
     *
     * @return the value of jd_computer.endtime
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_computer.endtime
     *
     * @param endtime the value for jd_computer.endtime
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}