package com.model.mapper;

import com.model.entity.JdComputer;

import java.util.List;

public interface JdComputerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_computer
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_computer
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    int insert(JdComputer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_computer
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    int insertSelective(JdComputer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_computer
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    JdComputer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_computer
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    int updateByPrimaryKeySelective(JdComputer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jd_computer
     *
     * @mbg.generated Tue Jun 25 22:19:43 CST 2019
     */
    int updateByPrimaryKey(JdComputer record);

    List<JdComputer> findAll();
}